mouse = true

timestamps = true
timestamps_before_author = true
timestamp_format = "3:04PM"

message_limits = 200
editor = "default"

[keys]
focus_guilds_tree = "Ctrl+G"
focus_messages_text = "Ctrl+T"
focus_message_input = "Ctrl+B"
toggle_guild_tree = "Ctrl+N"
select_previous = "Rune[k]"
select_next = "Rune[j]"
select_first = "Rune[g]"
select_last = "Rune[G]"

[keys.guilds_tree]
select_current = "Enter"

[keys.messages_text]
select_reply = "Rune[s]"
reply = "Rune[r]"
reply_mention = "Rune[R]"
delete = "Rune[d]"
yank = "Rune[y]"
open = "Rune[o]"

[keys.message_input]
send = "Enter"
editor = "Ctrl+E"
cancel = "Esc"

[theme]
border = true
border_color = "#6c7086"
border_padding = [0, 0, 1, 1]
title_color = "#f5c2e7"
background_color = "#1e1e2e"

[theme.guilds_tree]
auto_expand_folders = true
graphics = true

[theme.messages_text]
author_color = "#f5c2e7"
reply_indicator = "╭ "
