style:
    selected-row:
        text-color: "#585b70"
        background-color: "#f2cdcd"
    progress-modal:
        current-item-path-max-len: 0
    use-old-size-bar: false
sorting:
    by: ""
    order: ""
