local opts = {
  render_modes = { "n", "c" },
  anti_conceal = {
    enable = true,
    above = 1,
    below = 1,
  },
  checkbox = {
    enabled = true,
    position = "inline",
    unchecked = {
      icon = "✘ ",
      highlight = "RenderMarkdownUnchecked",
      scope_highlight = nil,
    },
    checked = {
      icon = "✔ ",
      highlight = "RenderMarkdownChecked",
      scope_highlight = "@markup.strikethrough",
    },
    custom = {
      todo = {
        rendered = "◯ ",
        highlight = "RenderMarkdownTodo",
        scope_highlight = nil,
      },
    },
  },
  heading = {
    enabled = true,
    sign = true,
    position = "overlay",
    icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
    signs = { "󰫎 " },
    width = "block",
    left_margin = 0,
    left_pad = 2,
    right_pad = 4,
    min_width = 0,
    border = false,
    border_virtual = false,
    border_prefix = false,
    above = "▄",
    below = "▀",
    backgrounds = {
      "RenderMarkdownH1Bg",
      "RenderMarkdownH2Bg",
      "RenderMarkdownH3Bg",
      "RenderMarkdownH4Bg",
      "RenderMarkdownH5Bg",
      "RenderMarkdownH6Bg",
    },
    foregrounds = {
      "RenderMarkdownH1",
      "RenderMarkdownH2",
      "RenderMarkdownH3",
      "RenderMarkdownH4",
      "RenderMarkdownH5",
      "RenderMarkdownH6",
    },
  },
  code = {
    enabled = true,
    sign = false,
    style = "full",
    position = "left",
    language_pad = 2,
    language_name = true,
    disable_background = { "diff" },
    width = "block",
    left_margin = 0,
    left_pad = 2,
    right_pad = 0,
    min_width = 45,
    border = "thin",
    above = "▄",
    below = "▀",
    highlight = "RenderMarkdownCode",
    highlight_inline = "RenderMarkdownCodeInline",
    highlight_language = nil,
  },
  quote = {
    enabled = true,
    icon = "▋",
    repeat_linebreak = true,
    win_options = {
      showbreak = { default = "", rendered = "  " },
      breakindent = { default = false, rendered = true },
      breakindentopt = { default = "", rendered = "" },
    },
    highlight = "RenderMarkdownQuote",
  },
  pipe_table = { preset = "round" },
  sign = {
    enabled = true,
    highlight = "RenderMarkdownSign",
  },
}
return opts
