[general]
initial-tool                = "brush"
copy-command                = "wl-copy"
disable-notifications       = false
primary-highlighter         = "block"
actions-on-enter            = ["save-to-clipboard"]
actions-on-escape           = ["exit"]
corner-roundness            = 3
annotation-size-factor      = 0.8
brush-smooth-history-size   = 5
no-window-decoration        = true

[font]
family = "JetBrainsMono Nerd Font"
style  = "SemiBold"

[color-palette]
palette = [
    "#f38ba8",
    "#89b4fa",
    "#cba6f7",
    "#f5c2e7",
    "#f9e2af",
    "#a6e3a1",
    "#11111b",
]
